services:

  influxdb2:
    image: influxdb:2.7.6
    container_name: influxdb2
    ports:
      - 8086:8086
      - 8083:8083
    volumes:
      - influxdb2-storage:/var/lib/influxdb
      - influxdb2-config:/etc/influxdb2
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}

  grafana:
    image: grafana/grafana-oss:main-ubuntu
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD:${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SECURITY_ADMIN_USER:${GF_SECURITY_ADMIN_USER}


volumes:
  influxdb2-storage:
  influxdb2-config:
  grafana-storage:

